config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end


  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(params_flat)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
     @flat = Flat.find(params[:id])
    if @flat.update(params_flat)
      redirect_to flat_path(@flat)
    else
      render :edit
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

private

  def params_flat
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h2>Edit flat <%= @flat.name %></h2>
<br>
<%= link_to  "Back to the list", flats_path %>

<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Publish a flat" %>
<% end %>

app/views/flats/index.html.erb
<div class="container">

<h1 class="mt-3">All flats</h1>

<div class="row">
  <%  @flats.each do |flat|%>
    <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="card flat-card" style="width: 18rem;">
              <img class="card-img-top" alt="Card image cap" src='<%= flat.image %>'>
                <div class="card-body">
                  <h5 class="card-title"><%= flat.name  %></h5>
                  <p class="card-text"><%= flat.address.truncate(30) %></p>
                    <div class="flat-figure">
                      <%# <div class="guests"> %>
                        <span class="line-figure"><i class="fas fa-user-friends"></i> <%= flat.number_of_guests %> - </span>
                      <%# </div> %>
                      <%# <div class="price"> %>
                        </span class="line-figure"><%= flat.price_per_night %> €/nuit  </span>
                      <%# </div> %>
                    </div>
                    <div class="card-link">
                      <%= link_to  "More info", flat_path(flat) %>
                      <%= link_to  "Edit", edit_flat_path(flat), class: 'text-warning' %>
                      <%= link_to "Delete", flat_path(flat),class: 'text-danger', method: :delete, data:{ confirm: "Delete the restaurant and the reviews" }  %>
                    </div>
                </div>
            </div>
    </div>
     <% end %>
</div>

app/views/flats/new.html.erb
<h2>Publish a new Flat</h2>


<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Publish a flat" %>
<% end %>

app/views/flats/show.html.erb
<div class="map" style="background-image: url('<%= @flat.image %>')"></div>
<div class="container">

<br>

<div class="content">
  <div class="row">

    <div class="col-lg-8 col-md-12">
      <div class="flat-show-card">
        <h1><%= @flat.name %></h1>
        <p><%= @flat.address %></p>
      </div>


      <div class="flat-show-card">
      <h2>A bit more about this flat...</h2>
      <p><%= @flat.description %></p>
      </div>
    </div>
    <div class="col-lg-4 col-md-12">
      <div class="flat-show-card">
        <h4>Book the flat</h4>
          <form action="" class="booking-form">
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">From:</span>
              <input type="text" class="form-control" placeholder="12/10/2017" aria-label="Username" aria-describedby="basic-addon1">
            </div>
            <div class="input-group mt-2">
              <span class="input-group-addon" id="basic-addon1">To:</span>
              <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username" aria-describedby="basic-addon1">
            </div>
            <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
          </form>
      </div>
      <div class="flat-show-card">
      <h4>Details</h4>
      <div class="flex ">
        <i class="fas fa-user-friends"></i> <%= @flat.number_of_guests %>
        <%= @flat.price_per_night %> <span>€</span>
      </div>
      </div>

    </div>
  </div>
</div>

<%= link_to  "Back to the list", flats_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script
      src="https://use.fontawesome.com/releases/v5.15.1/js/all.js"
      data-auto-a11y="true"
    ></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<%# navbar %>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/flats">Simple AirBnB</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      </li>
      </li>
      <li class="nav-item">
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <form class="form-inline my-2 my-lg-0">
<a class="btn btn-outline-primary my-2 my-sm-0 ml-2" href="/flats/new">Add Flat</a>
    </form>
  </div>
</nav>


  <body>


    <%= yield %>
  </body>

</html>